[build]
  command = "yarn cache clean --force && yarn install --frozen-lockfile && yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"
  NPM_FLAGS = "--prefer-offline --no-audit"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
