[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "8.15.0"
  NPM_FLAGS = "--prefer-offline --no-audit"

# Handle Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

