[build]
  command = "pnpm store prune && pnpm install && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "8.15.0"
  NPM_FLAGS = "--prefer-offline --no-audit"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
