export const onboardingOptions = {
  movies: [
    {
      id: "oppenheimer-2023",
      title: "Oppenheimer",
      year: 2023,
      genres: ["Biography", "Drama", "History"],
      image: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    },
    {
      id: "dune-part-two-2024",
      title: "Dune: Part Two",
      year: 2024,
      genres: ["Sci-Fi", "Adventure", "Action"],
      image: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    },
    {
      id: "barbie-2023",
      title: "Barbie",
      year: 2023,
      genres: ["Comedy", "Fantasy", "Adventure"],
      image: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    },
    {
      id: "spider-man-across-spider-verse-2023",
      title: "Spider-Man: Across the Spider-Verse",
      year: 2023,
      genres: ["Animation", "Superhero", "Adventure"],
      image: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    },
    {
      id: "john-wick-chapter-4-2023",
      title: "John Wick: Chapter 4",
      year: 2023,
      genres: ["Action", "Thriller", "Crime"],
      image: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    },
    {
      id: "a-quiet-place-2018",
      title: "A Quiet Place",
      year: 2018,
      genres: ["Horror", "Sci-Fi", "Thriller"],
      image: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    },
    {
      id: "rrr-2022",
      title: "RRR",
      year: 2022,
      genres: ["Action", "Historical", "Indian"],
      image: "/rrr.png",
    },
    {
      id: "3-idiots-2009",
      title: "3 Idiots",
      year: 2009,
      genres: ["Comedy", "Drama", "Indian"],
      image: "/3_idiots.png",
    },
  ],
  series: [
    {
      id: "house-of-the-dragon-2022",
      title: "House of the Dragon",
      year: "2022–",
      genres: ["Fantasy", "Drama", "Adventure"],
      image: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    },
    {
      id: "the-last-of-us-2023",
      title: "The Last of Us",
      year: "2023–",
      genres: ["Sci-Fi", "Thriller", "Post-Apocalyptic"],
      image: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    },
    {
      id: "wednesday-2022",
      title: "Wednesday",
      year: "2022–",
      genres: ["Comedy", "Horror", "Mystery"],
      image: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    },
    {
      id: "the-bear-2022",
      title: "The Bear",
      year: "2022–",
      genres: ["Slice of Life", "Dark Comedy", "Drama"],
      image: "/bear.png",
    },
    {
      id: "the-summer-i-turned-pretty-2022",
      title: "The Summer I Turned Pretty",
      year: "2022–",
      genres: ["Romance", "Coming-of-Age", "Teen Drama"],
      image: "/summer.png",
    },
    {
      id: "love-is-blind-2020",
      title: "Love Is Blind",
      year: "2020–",
      genres: ["Reality", "Romance", "Social Experiment"],
      image: "/love_blind.png",
    },
    {
      id: "sacred-games-2018",
      title: "Sacred Games",
      year: "2018–2019",
      genres: ["Crime", "Thriller", "Drama"],
      image: "/sacred_games.png",
    },
    {
      id: "modern-family-2009",
      title: "Modern Family",
      year: "2009–2020",
      genres: ["Sitcom", "Comedy", "Family"],
      image: "/modern_family.png",
    },
  ],
  songs: [
    {
      id: "midnights-2022",
      title: "Midnights",
      artist: "Taylor Swift",
      year: 2022,
      genres: ["Pop", "Synth-Pop", "Singer-Songwriter"],
      image: "https://i.scdn.co/image/ab67616d0000b273bb54dde68cd23e2a268ae0f5",
    },
    {
      id: "certified-lover-boy-2021",
      title: "Certified Lover Boy",
      artist: "Drake",
      year: 2021,
      genres: ["Hip-Hop", "Rap", "R&B"],
      image: "https://i.scdn.co/image/ab67616d0000b273bb54dde68cd23e2a268ae0f5",
    },
    {
      id: "guts-2023",
      title: "GUTS",
      artist: "Olivia Rodrigo",
      year: 2023,
      genres: ["Pop", "Pop-Rock", "Alternative"],
      image: "https://i.scdn.co/image/ab67616d0000b273bb54dde68cd23e2a268ae0f5",
    },
    {
      id: "aashiqui-2-ost-2013",
      title: "Aashiqui 2 OST",
      artist: "Arijit Singh",
      year: 2013,
      genres: ["Bollywood", "Romantic", "Soundtrack"],
      image: "https://i.scdn.co/image/ab67616d0000b273bb54dde68cd23e2a268ae0f5",
    },
    {
      id: "moner-manush-2008",
      title: "Moner Manush",
      artist: "Shreya Ghoshal",
      year: 2008,
      genres: ["Classical", "Playback", "Hindi Pop"],
      image: "https://i.scdn.co/image/ab67616d0000b273bb54dde68cd23e2a268ae0f5",
    },
    {
      id: "rockstar-ost-2011",
      title: "Rockstar OST",
      artist: "A. R. Rahman",
      year: 2011,
      genres: ["Bollywood", "Pop-Rock", "Soundtrack"],
      image: "https://i.scdn.co/image/ab67616d0000b273bb54dde68cd23e2a268ae0f5",
    },
    {
      id: "after-hours-2020",
      title: "After Hours",
      artist: "The Weeknd",
      year: 2020,
      genres: ["R&B", "Pop", "Synthwave"],
      image: "https://i.scdn.co/image/ab67616d0000b273bb54dde68cd23e2a268ae0f5",
    },
    {
      id: "30-2021",
      title: "30",
      artist: "Adele",
      year: 2021,
      genres: ["Soul", "Pop", "Ballad"],
      image: "https://i.scdn.co/image/ab67616d0000b273bb54dde68cd23e2a268ae0f5",
    },
  ],
  books: [
    {
      id: "the-midnight-library-2020",
      title: "The Midnight Library",
      author: "Matt Haig",
      year: 2020,
      genres: ["Fiction", "Fantasy", "Inspirational"],
      image: "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
    },
    {
      id: "atomic-habits-2018",
      title: "Atomic Habits",
      author: "James Clear",
      year: 2018,
      genres: ["Self-Help", "Non-Fiction", "Productivity"],
      image: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    },
    {
      id: "it-ends-with-us-2016",
      title: "It Ends with Us",
      author: "Colleen Hoover",
      year: 2016,
      genres: ["Romance", "Drama", "Contemporary"],
      image: "https://covers.openlibrary.org/b/isbn/9781501110368-L.jpg",
    },
    {
      id: "project-hail-mary-2021",
      title: "Project Hail Mary",
      author: "Andy Weir",
      year: 2021,
      genres: ["Sci-Fi", "Adventure", "Thriller"],
      image: "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
    },
    {
      id: "the-alchemist-1988",
      title: "The Alchemist",
      author: "Paulo Coelho",
      year: 1988,
      genres: ["Fiction", "Philosophy", "Inspirational"],
      image: "https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg",
    },
    {
      id: "the-white-tiger-2008",
      title: "The White Tiger",
      author: "Aravind Adiga",
      year: 2008,
      genres: ["Fiction", "Social Commentary", "Indian"],
      image: "https://covers.openlibrary.org/b/isbn/9781416562597-L.jpg",
    },
    {
      id: "the-palace-of-illusions-2008",
      title: "The Palace of Illusions",
      author: "Chitra Banerjee Divakaruni",
      year: 2008,
      genres: ["Mythology", "Historical Fiction", "Indian"],
      image: "/palace.png",
    },
    {
      id: "gone-girl-2012",
      title: "Gone Girl",
      author: "Gillan Flynn",
      year: 2012,
      genres: ["Thriller", "Mystery", "Crime"],
      image: "https://covers.openlibrary.org/b/isbn/9780307588364-L.jpg",
    },
  ],
};
